apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-querynode
  labels:
    app: milvus-querynode
    release: {{ .Release.Name }}
spec:
  type: "{{ .Values.milvus.service.type | default "ClusterIP" }}"
  selector:
    app: milvus-querynode
    release: {{ .Release.Name }}
  ports:
    - name: querynode
      port: {{ .Values.milvus.service.querynodePort | default 21121 }} 
      targetPort: {{ .Values.milvus.service.querynodePort | default 21121 }} 
      protocol: TCP #
