name: CI Pipeline for Digital Ocean

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image for backend services
        run: |
          docker build -t myusername/backend:latest -f docker/Dockerfile.backend .

      - name: Build Docker image for web scraper services
        run: |
          docker build -t myusername/webscraper:latest -f docker/Dockerfile.webscraper .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Backend Docker image
        run: |
          docker push myusername/backend:latest

      - name: Push Web Scraper Docker image
        run: |
          docker push myusername/webscraper:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Deploy Backend Services with Helm
        run: |
          helm upgrade --install backend-service ./helm/backend-chart \
            --set image.repository=myusername/backend \
            --set image.tag=latest
