name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Backend Services to Kubernetes
        run: |
          kubectl apply -f k8s/geodiscounts-deployment.yaml
          kubectl apply -f k8s/coupon_core-deployment.yaml
          kubectl apply -f k8s/authentication-deployment.yaml
          kubectl apply -f k8s/web_scraper-job.yaml
