backend:
  replicaCount: 1

  image:
    repository: my-backend-image
    tag: dev-latest
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8000

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"

  env:
    environment: development
    logLevel: debug

  nodeSelector: {}
  tolerations: []
  affinity: {}
