backend:
  replicaCount: 1

  image:
    repository: fakay96/backend  
    tag: ""
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8000

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1"

milvus:
  replicaCount: 1

  image:
    repository: milvusdb/milvus
    tag: "v2.2.12"
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 19530
    metricsPort: 9091

  logLevel: "debug"

  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"

  env:
    environment: development
    logLevel: debug
  nodeSelector: {}
  tolerations: []
  affinity: {}

datacoord:
  service:
    port: 13333

datanode:
  service:
    port: 21123

etcd:
  service:
    port: 2379

minio:
  service:
    port: 9000
    consolePort: 9001

querycoord:
  service:
    port: 19531

querynode:
  service:
    port: 21121
