backend:
  replicaCount: 1

  image:
    repository: fakay96/coupon-core 
    tag: ""
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8000

  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"

milvus:
  replicaCount: 1

  image:
    repository: milvusdb/milvus
    tag: "v2.2.12"
    pullPolicy: Always

  service:
    type: ClusterIP

  logLevel: "debug"

  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "2"

  nodeSelector: {}
  tolerations: []
  affinity: {}
