backend:
  replicaCount: 1

  image:
    repository: fakay96/backend  
    tag: ""
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8000

  resources:
    requests:
      memory: "256Mi"   # increased from 128Mi
      cpu: "200m"       # increased from 100m
    limits:
      memory: "512Mi"   # increased from 256Mi
      cpu: "1000m"      # increased from 500m


  env:
    environment: production
    logLevel: debug

  nodeSelector: {}
  tolerations: []
  affinity: {}
