backend:
  replicaCount: 1

  image:
    repository: fakay96/backend  
    tag: ""
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8000

  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

  nodeSelector:
    workload: backend

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: workload
            operator: In
            values:
            - backend

milvus:
  replicaCount: 1

  image:
    repository: milvusdb/milvus
    tag: "v2.2.12"
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 19530
    metricsPort: 9091

  logLevel: "debug"

  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  nodeSelector:
    workload: milvus

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: workload
            operator: In
            values:
            - milvus

  env:
    environment: staging
    logLevel: debug

datacoord:
  service:
    port: 13333

datanode:
  service:
    port: 21123

etcd:
  service:
    port: 2379

minio:
  service:
    port: 9000
    consolePort: 9001

querycoord:
  service:
    port: 19531

querynode:
  service:
    port: 21121

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: dishpal.ai
      paths:
        - path: /api
      pathType: Prefix
  tls:
    - hosts:
        - dishpal.ai
      secretName: dishpal-ai-tls

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

tolerations: []

affinity: {}
