namespace: production

wordpress:
  username: 
    secretKeyRef:
      name: wordpress-credentials
      key: username
  password: 
    secretKeyRef:
      name: wordpress-credentials
      key: password
  email: admin@dishpal.ai
  blogName: "DishPal Blog"
  
  mariadb:
    enabled: true
    auth:
      rootPassword: 
        secretKeyRef:
          name: mariadb-credentials
          key: rootPassword
      password: 
        secretKeyRef:
          name: mariadb-credentials
          key: password
      database: wordpress
      username: wordpress

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    host: dishpal.ai
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /

  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

  persistence:
    enabled: true
    size: "10Gi"
