apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.backend.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag}}"
          imagePullPolicy: "{{ .Values.backend.image.pullPolicy }}"
          ports:
            - containerPort: {{ .Values.backend.service.port  }}
          resources:
            requests:
              memory: "{{ .Values.backend.resources.requests.memory }}"
              cpu: "{{ .Values.backend.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.backend.resources.limits.memory }}"
              cpu: "{{ .Values.backend.resources.limits.cpu }}"
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_HOST
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ENVIRONMENT
            - name: GDAL_LIBRARY_PATH
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GDAL_LIBRARY_PATH
            - name: MILVUS_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MILVUS_HOST
            - name: MILVUS_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MILVUS_PORT
        - name: MILVUS_USER