apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.backend.replicaCount | default 1 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-milvus
        image: busybox:1.28
        command: 
        - sh
        - -c
        - until nc -z {{ .Release.Name }}-milvus 19530; do echo waiting for milvus; sleep 2; done;
      - name: wait-for-etcd
        image: busybox:1.28
        command: 
        - sh
        - -c
        - until nc -z {{ .Release.Name }}-etcd 2379; do echo waiting for etcd; sleep 2; done;
      - name: wait-for-minio
        image: busybox:1.28
        command: 
        - sh
        - -c
        - until nc -z {{ .Release.Name }}-minio 9000; do echo waiting for minio; sleep 2; done;
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: "{{ .Values.backend.image.pullPolicy }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          resources:
            requests:
              memory: "{{ .Values.backend.resources.requests.memory }}"
              cpu: "{{ .Values.backend.resources.requests.cup }}"
            limits:
              memory: "{{ .Values.backend.resources.limits.memory }}"
              cpu: "{{ .Values.backend.resources.limits.cpu }}"
          env:
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_HOST
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ENVIRONMENT
            - name: MILVUS_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MILVUS_HOST
            - name: MILVUS_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MILVUS_PORT
