apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-etcd
  labels:
    app: {{ .Release.Name }}-etcd
    release: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-etcd
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-etcd
        release: {{ .Release.Name }}
    spec:
      priorityClassName: core-services-priority
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.16
        env:
        - name: ETCD_AUTO_COMPACTION_MODE
          value: "revision"
        - name: ETCD_AUTO_COMPACTION_RETENTION
          value: "1000"
        - name: ETCD_QUOTA_BACKEND_BYTES
          value: "4294967296"
        - name: ETCD_SNAPSHOT_COUNT
          value: "50000"
        command: 
        - etcd
        - --advertise-client-urls=http://{{ .Release.Name }}-etcd.production.svc.cluster.local:2379
        - --listen-client-urls=http://0.0.0.0:2379
        - --data-dir=/etcd
        ports:
        - containerPort: 2379
        volumeMounts:
        - name: etcd-data
          mountPath: /etcd
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: etcd-data
        emptyDir: {}
