apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-milvus
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.milvus.replicaCount | default 1 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      priorityClassName: core-services-priority
      initContainers:
      - name: wait-for-etcd
        image: busybox:1.28
        command:
        - sh
        - -c
        - |
          echo "Waiting for ETCD..."
          timeout 60 sh -c 'until nc -z {{ .Release.Name }}-etcd.production.svc.cluster.local 2379; do echo waiting for etcd; sleep 2; done'
          echo "ETCD is ready!"

      - name: wait-for-minio
        image: busybox:1.28
        command:
        - sh
        - -c
        - |
          echo "Waiting for MinIO..."
          timeout 60 sh -c 'until nc -z {{ .Release.Name }}-minio.production.svc.cluster.local 9000; do echo waiting for minio; sleep 2; done'
          echo "MinIO is ready!"

      containers:
      - name: milvus
        image: "{{ .Values.milvus.image.repository }}:{{ .Values.milvus.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.milvus.image.pullPolicy | quote }}
        command: ["milvus", "run", "standalone"]  # Ensure Milvus starts correctly
        ports:
        - containerPort: 19530
        - containerPort: 9091
        env:
        - name: ETCD_ENDPOINTS
          value: "http://{{ .Release.Name }}-etcd.production.svc.cluster.local:2379"
        - name: MINIO_ADDRESS
          value: "http://{{ .Release.Name }}-minio.production.svc.cluster.local:9000"
        - name: MILVUS_LOG_LEVEL
          value: "{{ .Values.milvus.logLevel | default "debug" }}"
        resources:
          {{- toYaml .Values.milvus.resources | nindent 10 }}
