# Start from the base image built from Dockerfile.base
FROM fakay96/coupon-core:0.0.1

# Set working directory for the CELERY app
WORKDIR /app

# Expose the application port
EXPOSE 8000

# Add an entrypoint script for initialization
COPY Scripts/entryfile_backend.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# Use the entrypoint script for initialization
ENTRYPOINT ["/app/entrypoint.sh"]