# Start from the base image built from Dockerfile.base
FROM fakay96/coupon-core:0.0.1

# Set working directory for the CELERY app
WORKDIR /app

# Expose the application port
EXPOSE 8000

# Add an entrypoint script for initialization
COPY /Scripts/init_celery.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Use the entrypoint script for initialization
ENTRYPOINT ["/entrypoint.sh"]
