apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-etcd
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  ports:
    - name: etcd
      port: 2379
      targetPort: 2379
