apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-milvus
  labels:
    app: milvus-proxy
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.milvus.service.type | quote }}
  ports:
  - port: 19530
    targetPort: 19530
    protocol: TCP
    name: milvus
  - port: 9091
    targetPort: 9091
    protocol: TCP
    name: metrics
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
