apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-milvus
  labels:
    app: milvus-proxy
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.milvus.service.type | quote }}
  selector:
    app: milvus-proxy
    release: {{ .Release.Name }}
  ports:
    - name: milvus
      port: {{ .Values.milvus.service.port | default 19530 }}
      targetPort: {{ .Values.milvus.service.port | default 19530 }}
      protocol: TCP
    - name: metrics
      port: {{ .Values.milvus.service.metricsPort | default 9091 }}
      targetPort: {{ .Values.milvus.service.metricsPort | default 9091 }}
      protocol: TCP
