apiVersion: v1
kind: Service
metadata:
  name: coupon-service-minio
  namespace: production
  labels:
    app: coupon-service-minio
spec:
  type: ClusterIP
  selector:
    app: coupon-service-minio
  ports:
    - name: minio-api
      port: 9000
      targetPort: 9000
    - name: minio-console
      port: 9001
      targetPort: 9001
