apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-etcd
  labels:
    app: {{ .Release.Name }}-etcd
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.etcd.service.type | default "ClusterIP" | quote }}
  selector:
    app: {{ .Release.Name }}-etcd
    release: {{ .Release.Name }}
  ports:
    - name: etcd
      port: {{ .Values.etcd.service.port | default 2379 }}
      targetPort: {{ .Values.etcd.service.port | default 2379 }}
