# Generated by Django 5.1.7 on 2025-03-13 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's phone number in international format.", max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number in international format (e.g., +123456789).', regex='^\\+?[1-9]\\d{1,14}$')]),
        ),
    ]
