# Generated by Django 5.1.5 on 2025-04-26 16:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, help_text='Unique token for password reset.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the request was created.')),
                ('expires_at', models.DateTimeField(help_text='Timestamp when the token expires.')),
                ('used', models.BooleanField(default=False, help_text='Indicates whether the token has been used.')),
                ('user', models.ForeignKey(help_text='The user who requested the password reset.', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
