# Generated by Django 5.1.5 on 2025-05-05 13:29

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_passwordresetrequest"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", authentication.models.CustomUserManager()),
            ],
        ),
    ]
