# Generated by Django 5.1.5 on 2025-03-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activated_profile',
            field=models.BooleanField(blank=True, default=None, help_text='Indicates if the user has activated their profile.', null=True),
        ),
    ]
