# Generated by Django 5.1.5 on 2025-03-15 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_activated_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, help_text='Unique verification token for the user.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the verification token was created.')),
                ('expires_at', models.DateTimeField(help_text='Timestamp when the verification token expires.')),
                ('used', models.BooleanField(default=False, help_text='Indicates whether the verification token has been used.')),
                ('user', models.OneToOneField(help_text='The user associated with this verification record.', on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
