apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/resource-policy": keep

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  storageClassName: do-block-storage
{{- if not (lookup "v1" "PersistentVolumeClaim" .Release.Namespace "redis-pvc") }}
  volumeMode: Filesystem
{{- end }}
