# Generated by Django 5.1.5 on 2025-02-06 12:31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the retailer.', max_length=255, unique=True)),
                ('contact_info', models.TextField(blank=True, help_text='Contact details of the retailer.', null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Geographic location of the retailer (latitude/longitude).', srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the retailer was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the retailer was last updated.')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of the discount.')),
                ('discount_code', models.CharField(help_text='Unique code for redeeming the discount.', max_length=50, unique=True)),
                ('expiration_date', models.DateTimeField(help_text='Expiration date of the discount.')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Geographic location where the discount is valid (latitude/longitude).', srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the discount was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the discount was last updated.')),
                ('retailer', models.ForeignKey(help_text='Retailer providing the discount.', on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='geodiscounts.retailer')),
            ],
        ),
        migrations.CreateModel(
            name='SharedDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(help_text='Name of the group sharing the discount.', max_length=255)),
                ('participants', models.JSONField(help_text='List of participants sharing the discount (e.g., user IDs or emails).')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', help_text='Status of the shared discount.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the shared discount was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the shared discount was last updated.')),
                ('discount', models.ForeignKey(help_text='Discount being shared.', on_delete=django.db.models.deletion.CASCADE, related_name='shared_discounts', to='geodiscounts.discount')),
            ],
        ),
    ]
