# Generated by Django 5.2.1 on 2025-05-24 11:13

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import storages.backends.s3
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodiscounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Auto-generated from the first user turn.', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('user_preferences', models.JSONField(blank=True, default=dict, help_text='Lightweight prefs extracted in-chat.')),
                ('last_location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Last lat/lon supplied by the user.', null=True, srid=4326)),
                ('last_radius', models.FloatField(default=5000.0, help_text='Search radius (m) to assume when geo-filtering.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics_discussed', models.JSONField(default=list)),
                ('search_history', models.JSONField(default=list)),
                ('location_mentions', models.JSONField(default=list)),
                ('user_intent', models.CharField(blank=True, max_length=50)),
                ('stage', models.CharField(default='initial', help_text='Lifecycle stage: initial / developing / ongoing.', max_length=20)),
                ('avg_response_time', models.FloatField(blank=True, null=True)),
                ('successful_searches', models.IntegerField(default=0)),
                ('failed_searches', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conversation_contexts',
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('message_type', models.CharField(choices=[('greeting', 'Greeting'), ('search_query', 'Search Query'), ('search_results', 'Search Results'), ('conversation', 'Conversation'), ('error', 'Error'), ('system_info', 'System Info')], default='conversation', max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary structured data (token count, model name…).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conversation_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField(help_text='Raw user query.')),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Lon/lat used as search centre.', srid=4326)),
                ('radius', models.FloatField(default=5000.0, help_text='Radius in metres.')),
                ('search_context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('results', models.JSONField(blank=True, default=list)),
                ('result_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'search_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preference_type', models.CharField(choices=[('category', 'Category'), ('location', 'Location'), ('price_range', 'Price Range'), ('brand', 'Brand'), ('search_radius', 'Search Radius'), ('other', 'Other')], max_length=20)),
                ('key', models.CharField(help_text='Canonical preference key.', max_length=100)),
                ('value', models.TextField(help_text='Raw value (plain or JSON string).')),
                ('confidence', models.FloatField(default=0.5, help_text='0–1 confidence score from the extractor.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='retailer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='shareddiscount',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='discount',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=768),
        ),
        migrations.AddField(
            model_name='discount',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='product_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='source_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='stock_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='store_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='store_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='store_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='validity_dates',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, help_text='Optional SVG/PNG/JPEG stored in Spaces.', null=True, storage=storages.backends.s3.S3Storage(), upload_to='categories/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Human-friendly category name.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Optional thematic category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='geodiscounts.category'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='discount',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='image',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='discounts/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Where the offer can be redeemed.', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='discount',
            name='retailer',
            field=models.ForeignKey(help_text='Publisher of the discount.', on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='geodiscounts.retailer'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='analytics_data',
            field=models.JSONField(blank=True, default=dict, help_text='Arbitrary stats (sales, clicks…) collected downstream.'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='contact_info',
            field=models.TextField(blank=True, help_text='Address / phone / email.', null=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='WGS-84 lon/lat of the store HQ or flagship.', srid=4326),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='name',
            field=models.CharField(help_text='Public-facing retailer name.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Account that manages this retailer.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shareddiscount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shareddiscount',
            name='discount',
            field=models.ForeignKey(help_text='Underlying discount being shared.', on_delete=django.db.models.deletion.CASCADE, related_name='shared_discounts', to='geodiscounts.discount'),
        ),
        migrations.AlterField(
            model_name='shareddiscount',
            name='group_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shareddiscount',
            name='max_participants',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='shareddiscount',
            name='min_participants',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='shareddiscount',
            name='participants',
            field=models.JSONField(help_text='User IDs of participants.'),
        ),
        migrations.AlterField(
            model_name='shareddiscount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['is_active', 'expiration_date'], name='discounts_is_acti_aa84ab_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['location'], name='discounts_locatio_ed8b2c_idx'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='discount',
            table='discounts',
        ),
        migrations.AlterModelTable(
            name='retailer',
            table='retailers',
        ),
        migrations.AlterModelTable(
            name='shareddiscount',
            table='shared_discounts',
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversationcontext',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='geodiscounts.conversation'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='geodiscounts.conversation'),
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_requests', to='geodiscounts.conversation'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='search_request',
            field=models.ForeignKey(blank=True, help_text='Link if this message produced a search.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='geodiscounts.searchrequest'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_preferences', to='geodiscounts.conversation'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='extracted_from_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geodiscounts.conversationmessage'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='conversatio_user_id_e93dff_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status'], name='conversatio_status_742c74_idx'),
        ),
        migrations.AddIndex(
            model_name='searchrequest',
            index=models.Index(fields=['conversation', '-created_at'], name='search_requ_convers_85968a_idx'),
        ),
        migrations.AddIndex(
            model_name='searchrequest',
            index=models.Index(fields=['status'], name='search_requ_status_12b978_idx'),
        ),
        migrations.AddIndex(
            model_name='searchrequest',
            index=models.Index(fields=['location'], name='search_requ_locatio_df6c69_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='conversatio_convers_01af31_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['role', 'message_type'], name='conversatio_role_465d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['user', 'preference_type'], name='user_prefer_user_id_98103b_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['confidence'], name='user_prefer_confide_1650a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpreference',
            unique_together={('user', 'preference_type', 'key')},
        ),
    ]
