# Generated by Django 5.2.1 on 2025-05-24 15:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodiscounts', '0002_conversation_conversationcontext_conversationmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='WGS-84 lon/lat of the store HQ or flagship.', null=True, srid=4326),
        ),
    ]
