# Generated by Django 5.1.5 on 2025-03-14 11:32

import django.core.validators
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodiscounts', '0002_category_discount_image_alter_discount_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, help_text='Image representing the category, stored in S3 (supports SVG).', null=True, storage=storages.backends.s3.S3Storage(), upload_to='categories/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='discount',
            name='image',
            field=models.FileField(blank=True, help_text='Optional image representing the discount, stored in S3 (supports SVG).', null=True, storage=storages.backends.s3.S3Storage(), upload_to='discounts/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])]),
        ),
    ]
