# Generated by Django 5.1.7 on 2025-04-16 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodiscounts', '0002_alter_retailer_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='owner',
        ),
    ]
