# Generated by Django 5.1.5 on 2025-04-26 16:31

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodiscounts', '0003_remove_retailer_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocketDiscountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(help_text='Unique identifier for the WebSocket request', max_length=36, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Location for the discount search', srid=4326)),
                ('radius', models.FloatField(default=10.0, help_text='Search radius in kilometers')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of the request', max_length=20)),
                ('results', models.JSONField(blank=True, default=dict, help_text='Results of the request')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the request was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the request was last updated')),
                ('category', models.ForeignKey(blank=True, help_text='Category to filter by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='websocket_requests', to='geodiscounts.category')),
                ('user', models.ForeignKey(help_text='User who made the request', on_delete=django.db.models.deletion.CASCADE, related_name='websocket_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request_id'], name='geodiscount_request_fd77cc_idx'), models.Index(fields=['user'], name='geodiscount_user_id_9c2d9d_idx'), models.Index(fields=['status'], name='geodiscount_status_b539e7_idx'), models.Index(fields=['created_at'], name='geodiscount_created_be2082_idx')],
            },
        ),
    ]
