# Generated by Django 5.1.5 on 2025-04-30 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodiscounts', '0004_websocketdiscountrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the location.', max_length=255)),
                ('latitude', models.FloatField(help_text='Latitude coordinate (-90 to 90).', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(help_text='Longitude coordinate (-180 to 180).', validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('radius', models.FloatField(help_text='Radius in meters for the location.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('is_valid', models.BooleanField(default=True, help_text='Whether the location is valid.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When the location was last updated.')),
            ],
            options={
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='geodiscount_latitud_67dcf1_idx'), models.Index(fields=['is_valid'], name='geodiscount_is_vali_f21aae_idx'), models.Index(fields=['last_updated'], name='geodiscount_last_up_0132b5_idx')],
            },
        ),
    ]
