# Generated by Django 5.1.5 on 2025-05-02 06:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodiscounts', '0005_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websocketdiscountrequest',
            name='id',
        ),
        migrations.AddField(
            model_name='websocketdiscountrequest',
            name='conversation_history',
            field=models.JSONField(blank=True, default=list, help_text='History of conversation messages'),
        ),
        migrations.AddField(
            model_name='websocketdiscountrequest',
            name='websocket_url',
            field=models.URLField(blank=True, help_text='URL for WebSocket connection', max_length=500),
        ),
        migrations.AlterField(
            model_name='websocketdiscountrequest',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the WebSocket request', primary_key=True, serialize=False),
        ),
    ]
