# Generated by Django 5.1.5 on 2025-05-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geodiscounts", "0006_remove_websocketdiscountrequest_id_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="websocketdiscountrequest",
            name="geodiscount_user_id_9c2d9d_idx",
        ),
        migrations.RemoveField(
            model_name="websocketdiscountrequest",
            name="user",
        ),
        migrations.AddField(
            model_name="retailer",
            name="owner_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="ID of the user who owns/manages this retailer (cross-shard reference).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="websocketdiscountrequest",
            name="user_email",
            field=models.EmailField(
                blank=True,
                help_text="User email for quick reference without cross-shard query",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="websocketdiscountrequest",
            name="user_id",
            field=models.BigIntegerField(
                default=1, help_text="ID of the user who made the request"
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="websocketdiscountrequest",
            index=models.Index(
                fields=["user_id"], name="geodiscount_user_id_9c2d9d_idx"
            ),
        ),
    ]
