"""
Client IP Middleware

This middleware extracts the client's IP address from the incoming request and attaches it
to the `request` object as `client_ip`. It ensures that the IP address is globally available
for use across all views in the Django project.

The middleware prioritizes the `X-Forwarded-For` header to fetch the original client IP if the
request passes through a proxy. If the header is unavailable, it falls back to the `REMOTE_ADDR`
field.

Additionally, this middleware performs IP-based geolocation to determine the user's
longitude and latitude using a public geolocation API (ip-api.com). It caches the result
for 2 hours to reduce redundant external API calls and improve performance.

Attributes attached to request:
    - request.client_ip: The resolved IP address of the client.
    - request.client_latitude: Latitude of the client’s location (if resolved).
    - request.client_longitude: Longitude of the client’s location (if resolved).
"""

import requests
from typing import Callable
from django.core.cache import cache
from django.http import HttpRequest, HttpResponse


class UserLocationMiddleware:
    """
    Middleware to extract the client's IP address and attach it to the request object.
    Also attempts to geolocate the user by IP and cache the result.

    Attributes:
        get_response (Callable): The next middleware or view in the request chain.

    Methods:
        __call__(request: HttpRequest) -> HttpResponse:
            Processes the request and attaches client_ip, client_latitude, and client_longitude.
    """

    CACHE_TIMEOUT_SECONDS = 2 * 60 * 60  # 2 hours

    def __init__(self, get_response: Callable) -> None:
        """
        Initializes the middleware with the next middleware or view in the chain.

        Args:
            get_response (Callable): The next middleware or view to process the request.
        """
        self.get_response = get_response

    def __call__(self, request: HttpRequest) -> HttpResponse:
        """
        Processes the incoming request, extracts the client's IP address, and
        attaches it to the request object. Also attaches geolocated lat/lon values.

        Args:
            request (HttpRequest): The incoming HTTP request.

        Returns:
            HttpResponse: The HTTP response generated by the next middleware or view.
        """
        # Extract the IP address
        x_forwarded_for = request.META.get("HTTP_X_FORWARDED_FOR")
        ip = x_forwarded_for.split(",")[0] if x_forwarded_for else request.META.get("REMOTE_ADDR")
        request.client_ip = ip

        # Get geolocation from cache or API
        lat, lon = self.get_geo_location(ip)
        request.client_latitude = lat
        request.client_longitude = lon

        # Continue processing
        return self.get_response(request)

    def get_geo_location(self, ip: str) -> tuple[float | None, float | None]:
        """
        Query geolocation for the given IP and cache the result for 2 hours.

        Args:
            ip (str): IP address to look up.

        Returns:
            tuple: (latitude, longitude), or (None, None) if not available.
        """
        cache_key = f"geoip:{ip}"
        cached = cache.get(cache_key)

        if cached:
            return cached.get("lat"), cached.get("lon")

        try:
            response = requests.get(f"http://ip-api.com/json/{ip}", timeout=2)
            data = response.json()
            if data.get("status") == "success":
                lat, lon = data.get("lat"), data.get("lon")
                cache.set(cache_key, {"lat": lat, "lon": lon}, timeout=self.CACHE_TIMEOUT_SECONDS)
                return lat, lon
        except Exception:
            pass

        return 0, 0
