apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-rootcoord
  labels:
    app: milvus-rootcoord
    release: {{ .Release.Name }}
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: milvus-rootcoord
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: milvus-rootcoord
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: rootcoord
          image: "{{ .Values.milvus.image.repository }}:{{ .Values.milvus.image.tag | default .Chart.AppVersion }}"
          command: ["milvus", "run", "rootcoord"]
          ports:
            - containerPort: {{ .Values.milvus.service.rootcoordPort | default 53100 }}
          env:
            - name: ETCD_ENDPOINTS
              value: "http://{{ .Release.Name }}-etcd.production.svc.cluster.local:2379" 
            - name: MINIO_ADDRESS
              value: "http://{{ .Release.Name }}-minio.production.svc.cluster.local:9000"
          resources:
            requests:
              memory: "{{ .Values.milvus.resources.rootcoord.requests.memory | default "2Gi" }}"
              cpu: "{{ .Values.milvus.resources.rootcoord.requests.cpu | default "1000m" }}"
            limits:
              memory: "{{ .Values.milvus.resources.rootcoord.limits.memory | default "4Gi" }}"
              cpu: "{{ .Values.milvus.resources.rootcoord.limits.cpu | default "2000m" }}"
