name: Build Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Generate version information
      - name: Get version information
        id: get_version
        run: |
          VERSION_TAG=$(date +%Y%m%d)-${{ github.sha::0:7 }}
          echo "VERSION_TAG=${VERSION_TAG}" >> $GITHUB_ENV

      # Step 3: Build Docker images with version tag
      - name: Build Docker images
        env:
          VERSION_TAG: ${{ env.VERSION_TAG }}
        run: |
          docker build -t fakay96/backend:${VERSION_TAG} -f docker/Docker.backend .
          docker build -t fakay96/web_scraper:${VERSION_TAG} -f docker/Docker.web_scraper .

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Push Docker images to Docker Hub
      - name: Push Docker images
        env:
          VERSION_TAG: ${{ env.VERSION_TAG }}
        run: |
          docker push fakay96/backend:${VERSION_TAG}
          docker push fakay96/web_scraper:${VERSION_TAG}

      # Step 6: Save version tag for later use
      - name: Save version tag to file for later use
        run: |
          echo "Saving version tag to version.txt"
          echo "${VERSION_TAG}" > version.txt

      # Step 7: Upload version file as an artifact (optional)
      - name: Upload version file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: version-file
          path: version.txt
