name: Build Docker Images

on:
  workflow_call:
    inputs:
      tag:
        description: 'The commit SHA to use as a tag'
        required: false
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    runs-on: self-hosted
    outputs:
      version_tag: ${{ steps.get_version.outputs.version_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version information
        id: get_version
        run: |
          if [ -n "${{ inputs.tag }}" ]; then
            TAG=${{ inputs.tag }}
          else
            TAG=$(date +%Y%m%d)-$(echo "${GITHUB_SHA}" | cut -c1-7)
          fi
          echo "VERSION_TAG=${TAG}" >> "$GITHUB_ENV"
          echo "version_tag=${TAG}" >> "$GITHUB_OUTPUT"
        # Debug to verify version tag
      - name: Debug version tag
        run: echo "Generated version tag: ${{ steps.get_version.outputs.version_tag }}"

      - name: Build Docker images
        env:
          VERSION_TAG: ${{ env.VERSION_TAG }}
        run: |
          docker build --platform=linux/amd64 -t fakay96/backend:${VERSION_TAG} -f docker/Dockerfile.backend .
          docker build --platform=linux/amd64 -t fakay96/web_scraper:${VERSION_TAG} -f docker/Dockerfile.web_scraper .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images
        env:
          VERSION_TAG: ${{ env.VERSION_TAG }}
        run: |
          docker push fakay96/backend:${VERSION_TAG}
          docker push fakay96/web_scraper:${VERSION_TAG}

      - name: Upload version file as artifact
        run: echo "${VERSION_TAG}" > version.txt
        uses: actions/upload-artifact@v4
        with:
          name: version-file
          path: version.txt
