name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      tag: "0.0.1"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}



  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      version_tag: ${{ needs.build.outputs.version_tag }}
    secrets:
      KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
      KUBERNETES_SECRETS: ${{ secrets.KUBERNETES_SECRETS}}

  notify_failure:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Notify about failure 
        run: echo "CI Pipeline failed. Check logs for more details."

