name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      tag: ${{ github.sha }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  # test:
  #   needs: build
  #   uses: ./.github/workflows/test.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      version_tag: ${{ needs.build.outputs.version_tag }}

  notify_failure:
    runs-on: self-hosted
    if: failure()
    steps:
      - name: Notify about failure
        run: echo "CI Pipeline failed. Check logs for more details."
