name: Build Docker Images

on:
  workflow_call:
    inputs:
      tag:
        description: 'The commit SHA to use as a tag'
        required: false
        type: string

jobs:
  build:
    runs-on: self-hosted
    outputs:
      version_tag: ${{ steps.set_output.outputs.version_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version information
        id: get_version
        run: |
          if [ -n "${{ inputs.tag }}" ]; then
            TAG=${{ inputs.tag }}
          else
            TAG=$(date +%Y%m%d)-$(echo "${GITHUB_SHA}" | cut -c1-7)
          fi
          echo "VERSION_TAG=${TAG}" >> "$GITHUB_ENV"
          echo "version_tag=${TAG}" >> "$GITHUB_OUTPUT"

      - name: Build Docker images
        env:
          VERSION_TAG: ${{ env.VERSION_TAG }}
        run: |
          docker build -t fakay96/backend:${VERSION_TAG} -f docker/Docker.backend .
          docker build -t fakay96/web_scraper:${VERSION_TAG} -f docker/Docker.web_scraper .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images
        env:
          VERSION_TAG: ${{ env.VERSION_TAG }}
        run: |
          docker push fakay96/backend:${VERSION_TAG}
          docker push fakay96/web_scraper:${VERSION_TAG}

      - name: Save version tag to file
        run: echo "${VERSION_TAG}" > version.txt

      - name: Upload version file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: version-file
          path: version.txt

      - name: Set version tag as output
        id: set_output
        run: echo "version_tag=${VERSION_TAG}" >> "$GITHUB_OUTPUT"
