name: Deploy to DigitalOcean Kubernetes

on:
  workflow_call:
    inputs:
      version_tag:
        description: 'The version tag to deploy'
        required: true
        type: string
    secrets:
      KUBECONFIG_CONTENT:
        required: true

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure kubectl for DigitalOcean
        run: |
          mkdir -p ~/.kube
          echo "Creating kubeconfig from raw YAML content..."
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Verify kubeconfig file and access
        run: kubectl get nodes

      - name: Debug version tag
        run: 'echo "The version tag being used for deployment is: ${{ inputs.version_tag }}"'

      - name: Deploy backend service with Helm
        run: |
          helm upgrade --install backend-service ./k8s/backend \
            --set backend.image.repository=fakay96/backend \
            --set backend.image.tag=${{ inputs.version_tag }} \
            --namespace production --create-namespace \
            -f ./k8s/backend/values/production-values.yaml

      - name: Verify deployment status
        run: kubectl rollout status deployment backend -n production --timeout=10s
