name: Deploy to Kubernetes

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'The version tag to deploy'
        required: true
        type: string
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - staging
          - production
  push:
    branches:
      - main
  workflow_call:
    inputs:
      version_tag:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      KUBECONFIG_CONTENT:
        required: true
      KUBERNETES_SECRETS:
        required: true


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: |
          git fetch --all
          git checkout ${{ github.sha }}


      - name: Set environment variables
        run: |
          echo "NAMESPACE=${{ inputs.environment }}" >> $GITHUB_ENV
          echo "VERSION_TAG=${{ inputs.version_tag }}" >> $GITHUB_ENV

      - name: Configure kubectl for DigitalOcean
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Verify kubeconfig access
        run: kubectl get nodes

      - name: Ensure namespace exists
        run: |
          if ! kubectl get namespace ${{ env.NAMESPACE }}; then
            kubectl create namespace ${{ env.NAMESPACE }}
          fi

      - name: Deploy to staging
        if: github.ref == 'refs/heads/main'
        run: |
          helm upgrade --install coupon-service ./k8s/backend \
            --set backend.image.repository=fakay96/coupon-core \
            --set backend.image.tag=${{ env.VERSION_TAG }} \
            --namespace staging --create-namespace \
            -f ./k8s/backend/values/staging-values.yaml \
            --atomic --force --cleanup-on-fail --history-max 5 \
            --timeout 30m0s

      - name: Wait for production approval
        if: github.event.inputs.environment == 'production' || github.event_name == 'workflow_dispatch'
        run: |
          echo "Production deployment requires manual approval"
          echo "Please approve the deployment in the GitHub Actions UI"
          exit 1



      - name: Deploy services with Helm
        run: |
          helm upgrade --install coupon-service ./k8s/backend \
            --set backend.image.repository=fakay96/coupon-core \
            --set backend.image.tag=${{ env.VERSION_TAG }} \
            --namespace ${{ env.NAMESPACE }} --create-namespace \
            -f ./k8s/backend/values/${{ env.NAMESPACE }}-values.yaml \
            --atomic --force --cleanup-on-fail --history-max 5 \
            --timeout 30m0s

      - name: Verify service endpoints
        run: kubectl get endpoints coupon-service -n ${{ env.NAMESPACE }}

      - name: Debug pod logs on failure
        if: failure()
        run: kubectl logs -l app=backend -n ${{ env.NAMESPACE }} --tail=50

      - name: Rollback on failure
        if: failure()
        run: helm rollback coupon-service 1 --namespace ${{ env.NAMESPACE }}
