name: Deploy to Kubernetes

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'The version tag to deploy (leave blank to use artifact version)'
        required: false
        type: string
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - staging
          - production
  
  workflow_call:
    inputs:
      version_tag:
        required: false
        type: string
      environment:
        required: true
        type: string
    secrets:
      KUBECONFIG_CONTENT:
        required: true
      KUBERNETES_SECRETS:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    env:
      NAMESPACE: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download version artifact if version_tag not provided
        if: ${{ inputs.version_tag == '' }}
        uses: actions/download-artifact@v4
        with:
          name: version
          path: ./artifact

      - name: Set version tag
        id: set_version
        run: |
          if [ -z "${{ inputs.version_tag }}" ]; then
            VERSION_TAG=$(cat ./artifact/version.txt)
          else
            VERSION_TAG="${{ inputs.version_tag }}"
          fi
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
          echo "Version tag is $VERSION_TAG"

      - name: Debug input values
        run: |
          echo "NAMESPACE is: $NAMESPACE"
          echo "VERSION_TAG is: $VERSION_TAG"

      - name: Configure kubectl for DigitalOcean
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Verify kubeconfig access
        run: kubectl get nodes

      - name: Ensure namespace exists
        run: |
          kubectl get namespace $NAMESPACE || kubectl create namespace $NAMESPACE

      - name: Deploy Backend
        id: deploy_backend
        run: |
          if [ "$NAMESPACE" = "staging" ]; then
            helm upgrade --install coupon-service ./k8s/backend \
              --set backend.image.repository=fakay96/coupon-core \
              --set backend.image.tag=$VERSION_TAG \
              --namespace staging --create-namespace \
              -f ./k8s/backend/values/staging-values.yaml \
              --atomic --force --cleanup-on-fail --history-max 5 \
              --timeout 30m0s
          elif [ "$NAMESPACE" = "production" ]; then
            helm upgrade --install coupon-service ./k8s/backend \
              --set backend.image.repository=fakay96/coupon-core \
              --set backend.image.tag=$VERSION_TAG \
              --namespace production --create-namespace \
              -f ./k8s/backend/values/production-values.yaml \
              --atomic --force --cleanup-on-fail --history-max 5 \
              --timeout 30m0s
          else
            echo "Unknown environment: $NAMESPACE"
            exit 1
          fi

      - name: Deploy Frontend
        if: steps.deploy_backend.outcome == 'success'
        run: |
          if [ "$NAMESPACE" = "staging" ]; then
            helm upgrade --install frontend ./k8s/frontend \
              --set frontend.image.repository=fakay96/coupon-frontend \
              --set frontend.image.tag=$VERSION_TAG \
              --namespace staging --create-namespace \
              -f ./k8s/frontend/values/staging-values.yaml \
              --atomic --force --cleanup-on-fail --history-max 5 \
              --timeout 30m0s
          elif [ "$NAMESPACE" = "production" ]; then
            helm upgrade --install frontend ./k8s/frontend \
              --set frontend.image.repository=fakay96/coupon-frontend \
              --set frontend.image.tag=$VERSION_TAG \
              --namespace production --create-namespace \
              -f ./k8s/frontend/values/production-values.yaml \
              --atomic --force --cleanup-on-fail --history-max 5 \
              --timeout 30m0s
          else
            echo "Unknown environment: $NAMESPACE"
            exit 1
          fi

      - name: Verify service endpoints
        run: |
          kubectl get endpoints coupon-service -n $NAMESPACE
          kubectl get endpoints frontend -n $NAMESPACE
          if [ "$NAMESPACE" = "production" ]; then
            kubectl get endpoints wordpress -n $NAMESPACE
          fi

      - name: Debug pod logs on failure
        if: failure()
        run: |
          kubectl logs -l app=backend -n $NAMESPACE --tail=50
          kubectl logs -l app=frontend -n $NAMESPACE --tail=50
          if [ "$NAMESPACE" = "production" ]; then
            kubectl logs -l app=wordpress -n $NAMESPACE --tail=50
          fi

      - name: Rollback on failure
        if: failure()
        run: |
          helm rollback coupon-service 1 --namespace $NAMESPACE
          helm rollback frontend 1 --namespace $NAMESPACE
          if [ "$NAMESPACE" = "production" ]; then
            helm rollback wordpress 1 --namespace $NAMESPACE
          fi
