name: Run Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-c-2-fra1-01
    strategy:
      matrix:
        python-version: ['3.8', '3.10', '3.12']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run tests and generate report
        run: poetry run pytest --junitxml=report.xml

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: report.xml

      - name: Annotate failed tests
        if: ${{ failure() }}
        uses: dorny/test-reporter@v1
        with:
          name: pytest
          path: report.xml
          format: junit

      - name: Notify on failure
        if: ${{ failure() }}
        run: echo "Tests failed! Check the test report for details."
